version: '3.7'
services:
  web:
    build:
      context: .
      shm_size: 1G
    volumes: 
      - ./dist:/app/dist
    ports:
      - "8080:3000"
    environment:
      - IS_BUILD=true
  test:
    build:
      context: .
      shm_size: 1G
      dockerfile: Dockerfile-test
    environment:
      - IS_BUILD=false
      - CYPRESS_baseUrl=http://web:8080
